services:
    Bookboon\Api\Cache\RedisCache:
        public: false
        arguments: []

    Bookboon\Api\Bookboon:
        public: true
        factory: ['Bookboon\ApiBundle\Service\ApiFactory', create]
        arguments:
           - '@Bookboon\ApiBundle\Helper\ConfigurationHolder'
           - '@Bookboon\Api\Cache\Cache'