services:
    bookboon.cache:
        public: true
        class: Symfony\Component\Cache\Simple\RedisCache
        arguments:
          - '@default_redis_provider'
          - 'api'
          - 1800

    bookboon.handlerstack:
        class: GuzzleHttp\HandlerStack
        factory: ['GuzzleHttp\HandlerStack', 'create']

    Bookboon\Api\Bookboon:
        public: true
        lazy: true
        factory: ['Bookboon\ApiBundle\Service\ApiFactory', create]
        arguments:
          - '@Bookboon\ApiBundle\Helper\ConfigurationHolder'
          - '@bookboon.cache'
          - '@monolog.logger.api'
          - '@bookboon.handlerstack'
        tags:
          - { name: monolog.logger, channel: api }
