services:
  bookboon.cache.redis:
    class: Redis
    calls:
      - method: connect
        arguments:
          - '%env(REDIS_HOST)%'
          - '6379'

  bookboon.cache:
    public: true
    class: Symfony\Component\Cache\Simple\RedisCache
    arguments:
      - '@bookboon.cache.redis'
      - 'api'
      - 1800

  Bookboon\Api\Bookboon:
    public: true
    factory: ['Bookboon\ApiBundle\Service\ApiFactory', create]
    arguments:
      - '@Bookboon\ApiBundle\Helper\ConfigurationHolder'
      - '@bookboon.cache'